title: Vitor Oliveira | Red Team & Pentest
description: Security Research, Blog & Projects
url: https://vitor-oliveira84.github.io
author: Vitor Oliveira

# Jekyll configuration
markdown: kramdown
permalink: /blog/:year/:month/:day/:slug/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .nojekyll
